# Generated by Django 3.2.7 on 2021-09-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20210902_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='blog',
            field=models.TextField(max_length=600),
        ),
    ]
